apiVersion: kaptain.org/1.29
kind: layer-and-layerset-build
metadata:
  description: "Layerset composing quality and release settings for cluster-use projects"

spec:
  layers:
    - layerset-and-layer-build:[1.7]
